<?php

/**
 * @file
 * Primary module hooks for Magic User module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function magic_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.magic_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Integrates with the magic-login service for authentication and registration.') . '</p>';
  }

  return $output;
}

/**
 * Implements hook_theme().
 */
function magic_user_theme($existing, $type, $theme, $path) {
  return [
    'block__magic_login' => [
      'variables' => [
        'login_text' => NULL,
      ],
      'template' => 'magic-login',
      'path' => $path . '/templates/',
      'base hook' => 'block',
    ],
  ];
}
