# Schema for the configuration files of the Magic User module.
magic_user.settings:
  type: config_object
  label: 'Magic User settings'
  mapping:
    apikeysecret:
      type: string
      label: 'Api Key Secret'
    apikeypublic:
      type: string
      label: 'Api Key Publisheable'

block.settings.magic_user_magic_login_block:
  type: block_settings
  label: 'Magic Login Block'
  mapping:
    foo:
      type: string
      label: Foo
